In [ ]:
import pandas as pd   # Importing libraries for data manipulation
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
match_df = pd.read_csv("matches.csv")   # Reading the matches dataset

In [ ]:
match_df.columns  # Checking columns

Index(['id', 'season', 'city', 'date', 'match_type', 'player_of_match',
       'venue', 'team1', 'team2', 'toss_winner', 'toss_decision', 'winner',
       'result', 'result_margin', 'target_runs', 'target_overs', 'super_over',
       'method', 'umpire1', 'umpire2'],
      dtype='object')

In [ ]:
delivery_df = pd.read_csv("deliveries.csv") # Reading the deliveries dataset

In [ ]:
delivery_df.columns  # Checking columns

Index(['match_id', 'inning', 'batting_team', 'bowling_team', 'over', 'ball',
       'batter', 'bowler', 'non_striker', 'batsman_runs', 'extra_runs',
       'total_runs', 'extras_type', 'is_wicket', 'player_dismissed',
       'dismissal_kind', 'fielder'],
      dtype='object')

In [ ]:
match_df.head() # Display 1st 5 rows of matches dataset

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,241.0,20.0,N,NaN,MR Benson,SL Shastri
2,335984,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,130.0,20.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,2007/08,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,166.0,20.0,N,NaN,SJ Davis,DJ Harper
4,335986,2007/08,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,111.0,20.0,N,NaN,BF Bowden,K Hariharan

In [ ]:
delivery_df.head() # Display 1st 5 rows of deliveries dataset

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,SC Ganguly,P Kumar,BB McCullum,0,1,1,legbyes,0,NaN,NaN,NaN
1,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
2,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,SC Ganguly,0,1,1,wides,0,NaN,NaN,NaN
3,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
4,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN

In [ ]:
df = match_df.merge(delivery_df,left_on = 'id', right_on = 'match_id') # merging the deliveries and matches dataset

In [ ]:
df.head() # Display 1st 5 rows

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,...,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,...,P Kumar,BB McCullum,0,1,1,legbyes,0,NaN,NaN,NaN
1,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,...,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
2,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,...,P Kumar,SC Ganguly,0,1,1,wides,0,NaN,NaN,NaN
3,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,...,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
4,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,...,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN

In [ ]:
df.columns # Checking columns

Index(['id', 'season', 'city', 'date', 'match_type', 'player_of_match',
       'venue', 'team1', 'team2', 'toss_winner', 'toss_decision', 'winner',
       'result', 'result_margin', 'target_runs', 'target_overs', 'super_over',
       'method', 'umpire1', 'umpire2', 'match_id', 'inning', 'batting_team',
       'bowling_team', 'over', 'ball', 'batter', 'bowler', 'non_striker',
       'batsman_runs', 'extra_runs', 'total_runs', 'extras_type', 'is_wicket',
       'player_dismissed', 'dismissal_kind', 'fielder'],
      dtype='object')

In [ ]:
final_df = df[['id','inning', 'city', 'toss_winner', 'toss_decision', 'winner', 'target_runs', 'target_overs' , 'batting_team', 
       'bowling_team', 'over', 'ball', 'total_runs',
       'player_dismissed']]    # Selecting the required columns

In [ ]:
final_df.head() # Display 1st 5 rows

,id,inning,city,toss_winner,toss_decision,winner,target_runs,target_overs,batting_team,bowling_team,over,ball,total_runs,player_dismissed
0,335982,1,Bangalore,Royal Challengers Bangalore,field,Kolkata Knight Riders,223.0,20.0,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,1,NaN
1,335982,1,Bangalore,Royal Challengers Bangalore,field,Kolkata Knight Riders,223.0,20.0,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,0,NaN
2,335982,1,Bangalore,Royal Challengers Bangalore,field,Kolkata Knight Riders,223.0,20.0,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,1,NaN
3,335982,1,Bangalore,Royal Challengers Bangalore,field,Kolkata Knight Riders,223.0,20.0,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,0,NaN
4,335982,1,Bangalore,Royal Challengers Bangalore,field,Kolkata Knight Riders,223.0,20.0,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,0,NaN

In [ ]:
final_df['player_dismissed'] = final_df['player_dismissed'].apply(lambda x : 0 if pd.isna(x) else 1)  # Convering the player_dismissed columns to 0 and 1

C:\Users\Samundra\AppData\Local\Temp\ipykernel_12352\2476045002.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df['player_dismissed'] = final_df['player_dismissed'].apply(lambda x : 0 if pd.isna(x) else 1)

In [ ]:
final_df['player_dismissed'].unique() # Checking unique values

array([0, 1], dtype=int64)

In [ ]:
final_df.shape # checking the shape of the dataset

(260920, 14)

In [ ]:
final_df['current_run']=final_df.groupby(['inning','id'])['total_runs'].cumsum()  # calculating the current runs

C:\Users\Samundra\AppData\Local\Temp\ipykernel_12352\228791327.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df['current_run']=final_df.groupby(['inning','id'])['total_runs'].cumsum()

In [ ]:
final_df['required_run'] = final_df['target_runs'] - final_df['current_run'] # calculating the required runs

C:\Users\Samundra\AppData\Local\Temp\ipykernel_12352\1790970321.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df['required_run'] = final_df['target_runs'] - final_df['current_run']

In [ ]:
final_df['balls_left'] = 120 - final_df['over']*6 - final_df['ball']  # calculating the balls left

C:\Users\Samundra\AppData\Local\Temp\ipykernel_12352\3597347757.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df['balls_left'] = 120 - final_df['over']*6 - final_df['ball']

In [ ]:
final_df['player_down'] = final_df.groupby(['inning','id'])['player_dismissed'].cumsum() # calculating the wickets down

C:\Users\Samundra\AppData\Local\Temp\ipykernel_12352\830388495.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df['player_down'] = final_df.groupby(['inning','id'])['player_dismissed'].cumsum()

In [ ]:
final_df['wicket_left'] = 10 - final_df['player_down'] # calculating the wickets left

C:\Users\Samundra\AppData\Local\Temp\ipykernel_12352\4275953302.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df['wicket_left'] = 10 - final_df['player_down']

In [ ]:
final_df['current_rr'] = (final_df['current_run']*6)/(120-final_df['balls_left'])  # calculating the current run rate

C:\Users\Samundra\AppData\Local\Temp\ipykernel_12352\3604275484.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df['current_rr'] = (final_df['current_run']*6)/(120-final_df['balls_left'])

In [ ]:
final_df['required_rr'] = final_df['required_run']*6/final_df['balls_left'] # calculating the required runs rate

C:\Users\Samundra\AppData\Local\Temp\ipykernel_12352\920233272.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df['required_rr'] = final_df['required_run']*6/final_df['balls_left']

In [ ]:
final_df.head() # Display 1st 5 rows

,id,inning,city,toss_winner,toss_decision,winner,target_runs,target_overs,batting_team,bowling_team,...,ball,total_runs,player_dismissed,current_run,required_run,balls_left,player_down,wicket_left,current_rr,required_rr
0,335982,1,Bangalore,Royal Challengers Bangalore,field,Kolkata Knight Riders,223.0,20.0,Kolkata Knight Riders,Royal Challengers Bangalore,...,1,1,0,1,222.0,119,0,10,6.0,11.193277
1,335982,1,Bangalore,Royal Challengers Bangalore,field,Kolkata Knight Riders,223.0,20.0,Kolkata Knight Riders,Royal Challengers Bangalore,...,2,0,0,1,222.0,118,0,10,3.0,11.288136
2,335982,1,Bangalore,Royal Challengers Bangalore,field,Kolkata Knight Riders,223.0,20.0,Kolkata Knight Riders,Royal Challengers Bangalore,...,3,1,0,2,221.0,117,0,10,4.0,11.333333
3,335982,1,Bangalore,Royal Challengers Bangalore,field,Kolkata Knight Riders,223.0,20.0,Kolkata Knight Riders,Royal Challengers Bangalore,...,4,0,0,2,221.0,116,0,10,3.0,11.431034
4,335982,1,Bangalore,Royal Challengers Bangalore,field,Kolkata Knight Riders,223.0,20.0,Kolkata Knight Riders,Royal Challengers Bangalore,...,5,0,0,2,221.0,115,0,10,2.4,11.530435

In [ ]:
final_df.columns # Display columns

Index(['id', 'inning', 'city', 'toss_winner', 'toss_decision', 'winner',
       'target_runs', 'target_overs', 'batting_team', 'bowling_team', 'over',
       'ball', 'total_runs', 'player_dismissed', 'current_run', 'required_run',
       'balls_left', 'player_down', 'wicket_left', 'current_rr',
       'required_rr'],
      dtype='object')

In [ ]:
final_df.shape # checking the shape of dataset

(260920, 21)

In [ ]:
final_df = final_df[(final_df['inning'].isin([1,2]))] # Filtering the dataset for only 1st and 2nd innings

In [ ]:
final_df.shape  # checking the shape of dataset

(260759, 21)

In [ ]:
inn_2 = final_df[final_df['inning'] == 2]  # Filtering the dataset for only 2nd innings

In [ ]:
inn_2.shape  # checking the shape of dataset

(125741, 21)

In [ ]:
inn_2.head() # Display 1st 5 rows

,id,inning,city,toss_winner,toss_decision,winner,target_runs,target_overs,batting_team,bowling_team,...,ball,total_runs,player_dismissed,current_run,required_run,balls_left,player_down,wicket_left,current_rr,required_rr
124,335982,2,Bangalore,Royal Challengers Bangalore,field,Kolkata Knight Riders,223.0,20.0,Royal Challengers Bangalore,Kolkata Knight Riders,...,1,1,0,1,222.0,119,0,10,6.0,11.193277
125,335982,2,Bangalore,Royal Challengers Bangalore,field,Kolkata Knight Riders,223.0,20.0,Royal Challengers Bangalore,Kolkata Knight Riders,...,2,1,0,2,221.0,118,0,10,6.0,11.237288
126,335982,2,Bangalore,Royal Challengers Bangalore,field,Kolkata Knight Riders,223.0,20.0,Royal Challengers Bangalore,Kolkata Knight Riders,...,3,0,0,2,221.0,117,0,10,4.0,11.333333
127,335982,2,Bangalore,Royal Challengers Bangalore,field,Kolkata Knight Riders,223.0,20.0,Royal Challengers Bangalore,Kolkata Knight Riders,...,4,1,0,3,220.0,116,0,10,4.5,11.379310
128,335982,2,Bangalore,Royal Challengers Bangalore,field,Kolkata Knight Riders,223.0,20.0,Royal Challengers Bangalore,Kolkata Knight Riders,...,5,1,0,4,219.0,115,0,10,4.8,11.426087

In [ ]:
def result(row):  # Function to determine if the batting team won or not
    return 1 if row['winner'] == row['batting_team'] else 0

In [ ]:
inn_2['result'] = inn_2.apply(result,axis = 1) # Applying the result function to the dataset

C:\Users\Samundra\AppData\Local\Temp\ipykernel_12352\395550658.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  inn_2['result'] = inn_2.apply(result,axis = 1)

In [37]:
inn_2.head()

,id,inning,city,toss_winner,toss_decision,winner,target_runs,target_overs,batting_team,bowling_team,...,total_runs,player_dismissed,current_run,required_run,balls_left,player_down,wicket_left,current_rr,required_rr,result
124,335982,2,Bangalore,Royal Challengers Bangalore,field,Kolkata Knight Riders,223.0,20.0,Royal Challengers Bangalore,Kolkata Knight Riders,...,1,0,1,222.0,119,0,10,6.0,11.193277,0
125,335982,2,Bangalore,Royal Challengers Bangalore,field,Kolkata Knight Riders,223.0,20.0,Royal Challengers Bangalore,Kolkata Knight Riders,...,1,0,2,221.0,118,0,10,6.0,11.237288,0
126,335982,2,Bangalore,Royal Challengers Bangalore,field,Kolkata Knight Riders,223.0,20.0,Royal Challengers Bangalore,Kolkata Knight Riders,...,0,0,2,221.0,117,0,10,4.0,11.333333,0
127,335982,2,Bangalore,Royal Challengers Bangalore,field,Kolkata Knight Riders,223.0,20.0,Royal Challengers Bangalore,Kolkata Knight Riders,...,1,0,3,220.0,116,0,10,4.5,11.379310,0
128,335982,2,Bangalore,Royal Challengers Bangalore,field,Kolkata Knight Riders,223.0,20.0,Royal Challengers Bangalore,Kolkata Knight Riders,...,1,0,4,219.0,115,0,10,4.8,11.426087,0

In [ ]:
inn_2.columns # checking the columns

Index(['id', 'inning', 'city', 'toss_winner', 'toss_decision', 'winner',
       'target_runs', 'target_overs', 'batting_team', 'bowling_team', 'over',
       'ball', 'total_runs', 'player_dismissed', 'current_run', 'required_run',
       'balls_left', 'player_down', 'wicket_left', 'current_rr', 'required_rr',
       'result'],
      dtype='object')

In [39]:
final_data = inn_2[['batting_team','bowling_team','city','target_runs','required_run','balls_left','wicket_left','current_rr','required_rr','result']]

In [40]:
final_data.head()

,batting_team,bowling_team,city,target_runs,required_run,balls_left,wicket_left,current_rr,required_rr,result
124,Royal Challengers Bangalore,Kolkata Knight Riders,Bangalore,223.0,222.0,119,10,6.0,11.193277,0
125,Royal Challengers Bangalore,Kolkata Knight Riders,Bangalore,223.0,221.0,118,10,6.0,11.237288,0
126,Royal Challengers Bangalore,Kolkata Knight Riders,Bangalore,223.0,221.0,117,10,4.0,11.333333,0
127,Royal Challengers Bangalore,Kolkata Knight Riders,Bangalore,223.0,220.0,116,10,4.5,11.379310,0
128,Royal Challengers Bangalore,Kolkata Knight Riders,Bangalore,223.0,219.0,115,10,4.8,11.426087,0

In [ ]:
final_data = final_data[~final_data['batting_team'].isin(['Kochi Tuskers Kerala','Pune Warriors','Gujarat Lions','Rising Pune Supergiants','Rising Pune Supergiant'])
& ~final_data['bowling_team'].isin(['Kochi Tuskers Kerala','Pune Warriors','Gujarat Lions','Rising Pune Supergiants','Rising Pune Supergiant'])]

                       # Removing the teams which are no longer the part of IPL

In [42]:
final_data.shape

(112805, 10)

In [ ]:
final_data.replace(to_replace = 'Royal Challengers Bangalore', value = 'Royal Challengers Bengaluru',inplace = True)
final_data.replace(to_replace = 'Kings XI Punjab', value = 'Punjab Kings',inplace = True)
final_data.replace(to_replace = 'Delhi Daredevils', value = 'Delhi Capitals',inplace = True)
final_data.replace(to_replace = 'Deccan Chargers', value = 'Sunrisers Hyderabad',inplace = True)
     
# Replacing the old team names with new team names

In [ ]:
final_data = final_data.sample(final_data.shape[0]) # shuffling the dataset

In [ ]:
final_data.head() # Display 1st 5 rows

,batting_team,bowling_team,city,target_runs,required_run,balls_left,wicket_left,current_rr,required_rr,result
231502,Rajasthan Royals,Gujarat Titans,Ahmedabad,178.0,126.0,61,7,5.288136,12.393443,1
167909,Delhi Capitals,Punjab Kings,Chandigarh,167.0,30.0,23,7,8.474227,7.826087,0
200341,Sunrisers Hyderabad,Rajasthan Royals,Delhi,221.0,165.0,85,10,9.600000,11.647059,0
60078,Kolkata Knight Riders,Rajasthan Royals,Jaipur,165.0,162.0,115,10,3.600000,8.452174,0
259195,Punjab Kings,Rajasthan Royals,Guwahati,145.0,107.0,87,7,6.909091,7.379310,1

In [ ]:
final_data.isnull().sum() # checking for null values

batting_team       0
bowling_team       0
city            6012
target_runs        0
required_run       0
balls_left         0
wicket_left        0
current_rr         0
required_rr       16
result             0
dtype: int64

In [ ]:
final_data.dropna(inplace=True) # removing null values

In [ ]:
final_data = final_data[final_data['balls_left']!=0] # removing the rows where balls left is 0 (it makes infinite values in required_rr)

In [ ]:
final_data.info() # checking the info of the dataset

<class 'pandas.core.frame.DataFrame'>
Index: 106427 entries, 231502 to 225370
Data columns (total 10 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   batting_team  106427 non-null  object
 1   bowling_team  106427 non-null  object
 2   city          106427 non-null  object
 3   target_runs   106427 non-null  float64
 4   required_run  106427 non-null  float64
 5   balls_left    106427 non-null  int64
 6   wicket_left   106427 non-null  int64
 7   current_rr    106427 non-null  float64
 8   required_rr   106427 non-null  float64
 9   result        106427 non-null  int64
dtypes: float64(4), int64(3), object(3)
memory usage: 8.9+ MB

In [ ]:
final_data.describe() # checking the statistical measures of the dataset

,target_runs,required_run,balls_left,wicket_left,current_rr,required_rr,result
count,106427.000000,106427.000000,106427.000000,106427.000000,106427.000000,106427.000000,106427.000000
mean,169.144935,94.511524,62.950078,7.517209,7.628711,10.674642,0.517049
std,31.475622,51.024426,33.302916,2.153557,2.377280,14.133668,0.499712
min,43.000000,-10.000000,-3.000000,0.000000,0.000000,-516.000000,0.000000
25%,149.000000,54.000000,35.000000,6.000000,6.409091,7.304348,0.000000
50%,169.000000,93.000000,64.000000,8.000000,7.636364,9.057692,1.000000
75%,189.000000,132.000000,92.000000,9.000000,8.896552,11.250000,1.000000
max,288.000000,287.000000,119.000000,10.000000,36.000000,714.000000,1.000000

In [ ]:
final_data.shape # checking the shape of dataset

(106427, 10)

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score
 
             # Importing libraries for model building and evaluation

In [ ]:
x = final_data.drop(columns=['result']) # independent features
y = final_data['result'] # dependent features

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=5) # splitting the dataset into training and testing set

In [ ]:
trf = ColumnTransformer([  
    ('ohe',OneHotEncoder(sparse_output=False, drop='first'),['batting_team','bowling_team','city'])
],remainder='passthrough')  # Column transformer for one hot encoding the categorical features

In [ ]:
pipe = Pipeline(steps = [
    ('step1',trf),
    ('step2',LogisticRegression(solver = 'liblinear') )
])                                                        # Creating a pipeline for the model

In [ ]:
pipe.fit(x_train,y_train) # fitting the model

C:\Users\Samundra\anaconda3\Lib\site-packages\sklearn\compose\_column_transformer.py:1623: FutureWarning:
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(

Pipeline(steps=[('step1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('ohe',
                                                  OneHotEncoder(drop='first',
                                                                sparse_output=False),
                                                  ['batting_team',
                                                   'bowling_team', 'city'])])),
                ('step2', LogisticRegression(solver='liblinear'))])

In [ ]:
y_pred = pipe.predict(x_test) # predicting the values

In [ ]:
accuracy_score(y_test,y_pred) # checking the accuracy of the model

0.8010429390209527

In [60]:
sample = pd.DataFrame([{
    'batting_team': 'Delhi Capitals',
    'bowling_team': 'Royal Challengers Bengaluru',
    'city': 'Bengaluru',
    'target_runs': 150.0,
    'required_run': 97.0,
    'balls_left': 86,
    'wicket_left': 9,
    'current_rr': 9.352941,
    'required_rr': 6.767442
}])

In [61]:
print(pipe.predict_proba(sample))

[[0.09946337 0.90053663]]

In [ ]:
import pickle 
pickle.dump(pipe,open('pipe.pkl','wb'))  # saving the model to the local system